const traducciones = {
  "españa": "spain",
  "italia": "italy",
  "alemania": "germany",
  "republica dominicana": "dominican republic",
  "estados unidos": "united states",
  "reino unido": "united kingdom",
  "francia": "france",
  "colombia": "colombia",
  "méxico": "mexico",
  "canada": "canada",
  "argentina": "argentina",
  "brazil": "brazil",
  "chile": "chile",
  "peru": "peru",
  "japon": "japan",
  "china": "china",
  "india": "india",
  "rusia": "russia",
  "australia": "australia",
  "sudafrica": "south africa",
  "sudáfrica": "south africa",
  "noruega": "norway",
  "suecia": "sweden",
  "suiza": "switzerland",
  "finlandia": "finland",
  "portugal": "portugal",
  "polonia": "poland",
  "grecia": "greece",
  "turquia": "turkey",
  "ucraniana": "ukraine",
  "bielorrusia": "belarus",
  "belgica": "belgium",
  "dinamarca": "denmark",
  "eslovenia": "slovenia",
  "eslovaquia": "slovakia",
  "croacia": "croatia",
  "serbia": "serbia",
  "bosnia y herzegovina": "bosnia and herzegovina",
  "albania": "albania",
  "macedonia": "north macedonia",
  "kosovo": "kosovo",
  "montenegro": "montenegro",
  "andorra": "andorra",
  "armenia": "armenia",
  "azerbaiyan": "azerbaijan",
  "georgia": "georgia",
  "kazajistan": "kazakhstan",
  "kirguistan": "kyrgyzstan",
  "tajikistan": "tajikistan",
  "turkmenistan": "turkmenistan",
  "uzbekistan": "uzbekistan",
  "afganistan": "afghanistan",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
  "malasia": "malaysia",
  "singapur": "singapore",
  "brunei": "brunei",
  "indonesia": "indonesia",
  "filipinas": "philippines",
  "corea del sur": "south korea",
  "corea del norte": "north korea",
  "mongolia": "mongolia",
  "japon": "japan",
  "nepal": "nepal",
  "bhutan": "bhutan",
  "maldivas": "maldives",
  "pakistan": "pakistan",
  "bangladesh": "bangladesh",
  "nepal": "nepal",
  "sri lanka": "sri lanka",
  "birmania": "myanmar",
  "tailandia": "thailand",
  "laos": "laos",
  "camboya": "cambodia",
  "vietnam": "vietnam",
};
 
